apiVersion: v1
data:
  {{- if eq .Values.wavefront.AuthType "wavefront-token"}}
  token: {{ .Values.wavefront.token  | b64enc }}
  {{- end }}
  {{- if eq .Values.wavefront.AuthType "csp-api-token"}}
  cspApiTokenId: {{ .Values.wavefront.cspApiToken | b64enc }}
  {{- end }}
  {{- if eq .Values.wavefront.AuthType "csp-app-oauth"}}
  cspAppSecret: {{ .Values.wavefront.cspAppSecret  | b64enc }}
  cspAppId: {{ .Values.wavefront.cspAppId  | b64enc }}
  cspOrgId: {{ .Values.wavefront.cspOrgId  | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: wf-token
  namespace: {{ .Release.Namespace   }}
type: Opaque
